### ISSUE TITLE
Occasional Minor Formatting Issues

### ISSUE THREAD

**Issue by PRGilland** [scbroede/dq4-partychat-patcher#1]
Hello, thank you for making this patcher. It essentially makes the DS version the definitive experience, aside from smaller quality of life and statistical alterations added in the mobile version. I am up to Psaro's castle near the end of Chapter 5 and encountered no significant issues or game-breaking problems.

However, I have noticed some minor formatting issues that crop up very rarely in the party chat dialogue, where some text near the end of a sentence will break into new lines in the dialogue box.

I have almost exclusively noticed it on Alena, which initially led me to believe it was a quirky localization thing, but one instance have I seen it happen to Meena, which means it may be present on other characters at other points as well. I am unsure if this occurs in the mobile version. I haven't noticed any issues within other dialogue outside of party chat.

I figured this was worth pointing out, since this is still in beta, and the issues seem superficial enough to not negatively impact the experience as far as I can tell.

![SteamLink_2024-02-13_20-09-27](https://github.com/scbroede/dq4-partychat-patcher/assets/53190048/613a23d0-3921-4568-8b83-2bac9b29af4b)
![SteamLink_2024-02-13_20-09-02](https://github.com/scbroede/dq4-partychat-patcher/assets/53190048/8a409910-3060-4a79-9fdb-69d9e06f229f)
![SteamLink_2024-02-13_20-08-47](https://github.com/scbroede/dq4-partychat-patcher/assets/53190048/c409de84-3b0e-47e2-b59d-98a994e6a35c)

**Comment by scbroede** [comment]
guessing that the mobile script is manually specifying newlines in those strings instead of relying on the automatic line wraps for whatever reason, and this causes issues in the ds version due to different font/screen sizes. thanks for reporting, will look into it

**Comment by scbroede** [comment]
should be fixed with the latest version:
![image](https://github.com/scbroede/dq4-partychat-patcher/assets/32247405/344f06d8-15df-4757-bbd1-c36533a8b660)
(ignore the fact that i'm in the wrong place for that dialogue, i cheated to make it appear for testing purposes)

if you still have a copy of the repacked rom resulting from the 8th step in the readme, you can just apply the updated xdelta to that instead of having to go through all the steps again.

closing this for now but feel free to reopen if i missed anything

**Comment by PRGilland** [comment]
While I was testing the updated rom, while I haven't seen any of the formatting issue, I did notice the placement of a wrong pronoun for Sofia on the overworld after wearing the Zenithian armor. It might actually be an oversight on the mobile version, and maybe there might be more present.

![melonDS_2024-02-17_22-21-44](https://github.com/scbroede/dq4-partychat-patcher/assets/53190048/e3615b08-f285-45c3-8937-4383b1079812)

**Comment by scbroede** [comment]
yeah, that's a mistake in the mobile script. i fix those anyway when i find them, so i'll take care of it

**Comment by scbroede** [comment]
should be fixed now:
![image](https://github.com/scbroede/dq4-partychat-patcher/assets/32247405/841be451-c913-4c2d-83c4-aaff4f4f4785)

**Comment by PRGilland** [comment]
Seems to work fine now, thank you. I'll keep you posted if I encounter any more bugs.
